<?php

namespace Database\Seeders;

use App\Models\Kabupaten;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KabupatenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = array(
            array("id"=>"1101","provinsi_id"=>"11","kabupaten"=>"KABUPATEN SIMEULUE"),
            array("id"=>"1102","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH SINGKIL"),
            array("id"=>"1103","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH SELATAN"),
            array("id"=>"1104","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH TENGGARA"),
            array("id"=>"1105","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH TIMUR"),
            array("id"=>"1106","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH TENGAH"),
            array("id"=>"1107","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH BARAT"),
            array("id"=>"1108","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH BESAR"),
            array("id"=>"1109","provinsi_id"=>"11","kabupaten"=>"KABUPATEN PIDIE"),
            array("id"=>"1110","provinsi_id"=>"11","kabupaten"=>"KABUPATEN BIREUEN"),
            array("id"=>"1111","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH UTARA"),
            array("id"=>"1112","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH BARAT DAYA"),
            array("id"=>"1113","provinsi_id"=>"11","kabupaten"=>"KABUPATEN GAYO LUES"),
            array("id"=>"1114","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH TAMIANG"),
            array("id"=>"1115","provinsi_id"=>"11","kabupaten"=>"KABUPATEN NAGAN RAYA"),
            array("id"=>"1116","provinsi_id"=>"11","kabupaten"=>"KABUPATEN ACEH JAYA"),
            array("id"=>"1117","provinsi_id"=>"11","kabupaten"=>"KABUPATEN BENER MERIAH"),
            array("id"=>"1118","provinsi_id"=>"11","kabupaten"=>"KABUPATEN PIDIE JAYA"),
            array("id"=>"1171","provinsi_id"=>"11","kabupaten"=>"KOTA BANDA ACEH"),
            array("id"=>"1172","provinsi_id"=>"11","kabupaten"=>"KOTA SABANG"),
            array("id"=>"1173","provinsi_id"=>"11","kabupaten"=>"KOTA LANGSA"),
            array("id"=>"1174","provinsi_id"=>"11","kabupaten"=>"KOTA LHOKSEUMAWE"),
            array("id"=>"1175","provinsi_id"=>"11","kabupaten"=>"KOTA SUBULUSSALAM"),
            array("id"=>"1201","provinsi_id"=>"12","kabupaten"=>"KABUPATEN NIAS"),
            array("id"=>"1202","provinsi_id"=>"12","kabupaten"=>"KABUPATEN MANDAILING NATAL"),
            array("id"=>"1203","provinsi_id"=>"12","kabupaten"=>"KABUPATEN TAPANULI SELATAN"),
            array("id"=>"1204","provinsi_id"=>"12","kabupaten"=>"KABUPATEN TAPANULI TENGAH"),
            array("id"=>"1205","provinsi_id"=>"12","kabupaten"=>"KABUPATEN TAPANULI UTARA"),
            array("id"=>"1206","provinsi_id"=>"12","kabupaten"=>"KABUPATEN TOBA SAMOSIR"),
            array("id"=>"1207","provinsi_id"=>"12","kabupaten"=>"KABUPATEN LABUHAN BATU"),
            array("id"=>"1208","provinsi_id"=>"12","kabupaten"=>"KABUPATEN ASAHAN"),
            array("id"=>"1209","provinsi_id"=>"12","kabupaten"=>"KABUPATEN SIMALUNGUN"),
            array("id"=>"1210","provinsi_id"=>"12","kabupaten"=>"KABUPATEN DAIRI"),
            array("id"=>"1211","provinsi_id"=>"12","kabupaten"=>"KABUPATEN KARO"),
            array("id"=>"1212","provinsi_id"=>"12","kabupaten"=>"KABUPATEN DELI SERDANG"),
            array("id"=>"1213","provinsi_id"=>"12","kabupaten"=>"KABUPATEN LANGKAT"),
            array("id"=>"1214","provinsi_id"=>"12","kabupaten"=>"KABUPATEN NIAS SELATAN"),
            array("id"=>"1215","provinsi_id"=>"12","kabupaten"=>"KABUPATEN HUMBANG HASUNDUTAN"),
            array("id"=>"1216","provinsi_id"=>"12","kabupaten"=>"KABUPATEN PAKPAK BHARAT"),
            array("id"=>"1217","provinsi_id"=>"12","kabupaten"=>"KABUPATEN SAMOSIR"),
            array("id"=>"1218","provinsi_id"=>"12","kabupaten"=>"KABUPATEN SERDANG BEDAGAI"),
            array("id"=>"1219","provinsi_id"=>"12","kabupaten"=>"KABUPATEN BATU BARA"),
            array("id"=>"1220","provinsi_id"=>"12","kabupaten"=>"KABUPATEN PADANG LAWAS UTARA"),
            array("id"=>"1221","provinsi_id"=>"12","kabupaten"=>"KABUPATEN PADANG LAWAS"),
            array("id"=>"1222","provinsi_id"=>"12","kabupaten"=>"KABUPATEN LABUHAN BATU SELATAN"),
            array("id"=>"1223","provinsi_id"=>"12","kabupaten"=>"KABUPATEN LABUHAN BATU UTARA"),
            array("id"=>"1224","provinsi_id"=>"12","kabupaten"=>"KABUPATEN NIAS UTARA"),
            array("id"=>"1225","provinsi_id"=>"12","kabupaten"=>"KABUPATEN NIAS BARAT"),
            array("id"=>"1271","provinsi_id"=>"12","kabupaten"=>"KOTA SIBOLGA"),
            array("id"=>"1272","provinsi_id"=>"12","kabupaten"=>"KOTA TANJUNG BALAI"),
            array("id"=>"1273","provinsi_id"=>"12","kabupaten"=>"KOTA PEMATANG SIANTAR"),
            array("id"=>"1274","provinsi_id"=>"12","kabupaten"=>"KOTA TEBING TINGGI"),
            array("id"=>"1275","provinsi_id"=>"12","kabupaten"=>"KOTA MEDAN"),
            array("id"=>"1276","provinsi_id"=>"12","kabupaten"=>"KOTA BINJAI"),
            array("id"=>"1277","provinsi_id"=>"12","kabupaten"=>"KOTA PADANGSIDIMPUAN"),
            array("id"=>"1278","provinsi_id"=>"12","kabupaten"=>"KOTA GUNUNGSITOLI"),
            array("id"=>"1301","provinsi_id"=>"13","kabupaten"=>"KABUPATEN KEPULAUAN MENTAWAI"),
            array("id"=>"1302","provinsi_id"=>"13","kabupaten"=>"KABUPATEN PESISIR SELATAN"),
            array("id"=>"1303","provinsi_id"=>"13","kabupaten"=>"KABUPATEN SOLOK"),
            array("id"=>"1304","provinsi_id"=>"13","kabupaten"=>"KABUPATEN SIJUNJUNG"),
            array("id"=>"1305","provinsi_id"=>"13","kabupaten"=>"KABUPATEN TANAH DATAR"),
            array("id"=>"1306","provinsi_id"=>"13","kabupaten"=>"KABUPATEN PADANG PARIAMAN"),
            array("id"=>"1307","provinsi_id"=>"13","kabupaten"=>"KABUPATEN AGAM"),
            array("id"=>"1308","provinsi_id"=>"13","kabupaten"=>"KABUPATEN LIMA PULUH KOTA"),
            array("id"=>"1309","provinsi_id"=>"13","kabupaten"=>"KABUPATEN PASAMAN"),
            array("id"=>"1310","provinsi_id"=>"13","kabupaten"=>"KABUPATEN SOLOK SELATAN"),
            array("id"=>"1311","provinsi_id"=>"13","kabupaten"=>"KABUPATEN DHARMASRAYA"),
            array("id"=>"1312","provinsi_id"=>"13","kabupaten"=>"KABUPATEN PASAMAN BARAT"),
            array("id"=>"1371","provinsi_id"=>"13","kabupaten"=>"KOTA PADANG"),
            array("id"=>"1372","provinsi_id"=>"13","kabupaten"=>"KOTA SOLOK"),
            array("id"=>"1373","provinsi_id"=>"13","kabupaten"=>"KOTA SAWAH LUNTO"),
            array("id"=>"1374","provinsi_id"=>"13","kabupaten"=>"KOTA PADANG PANJANG"),
            array("id"=>"1375","provinsi_id"=>"13","kabupaten"=>"KOTA BUKITTINGGI"),
            array("id"=>"1376","provinsi_id"=>"13","kabupaten"=>"KOTA PAYAKUMBUH"),
            array("id"=>"1377","provinsi_id"=>"13","kabupaten"=>"KOTA PARIAMAN"),
            array("id"=>"1401","provinsi_id"=>"14","kabupaten"=>"KABUPATEN KUANTAN SINGINGI"),
            array("id"=>"1402","provinsi_id"=>"14","kabupaten"=>"KABUPATEN INDRAGIRI HULU"),
            array("id"=>"1403","provinsi_id"=>"14","kabupaten"=>"KABUPATEN INDRAGIRI HILIR"),
            array("id"=>"1404","provinsi_id"=>"14","kabupaten"=>"KABUPATEN PELALAWAN"),
            array("id"=>"1405","provinsi_id"=>"14","kabupaten"=>"KABUPATEN S I A K"),
            array("id"=>"1406","provinsi_id"=>"14","kabupaten"=>"KABUPATEN KAMPAR"),
            array("id"=>"1407","provinsi_id"=>"14","kabupaten"=>"KABUPATEN ROKAN HULU"),
            array("id"=>"1408","provinsi_id"=>"14","kabupaten"=>"KABUPATEN BENGKALIS"),
            array("id"=>"1409","provinsi_id"=>"14","kabupaten"=>"KABUPATEN ROKAN HILIR"),
            array("id"=>"1410","provinsi_id"=>"14","kabupaten"=>"KABUPATEN KEPULAUAN MERANTI"),
            array("id"=>"1471","provinsi_id"=>"14","kabupaten"=>"KOTA PEKANBARU"),
            array("id"=>"1473","provinsi_id"=>"14","kabupaten"=>"KOTA D U M A I"),
            array("id"=>"1501","provinsi_id"=>"15","kabupaten"=>"KABUPATEN KERINCI"),
            array("id"=>"1502","provinsi_id"=>"15","kabupaten"=>"KABUPATEN MERANGIN"),
            array("id"=>"1503","provinsi_id"=>"15","kabupaten"=>"KABUPATEN SAROLANGUN"),
            array("id"=>"1504","provinsi_id"=>"15","kabupaten"=>"KABUPATEN BATANG HARI"),
            array("id"=>"1505","provinsi_id"=>"15","kabupaten"=>"KABUPATEN MUARO JAMBI"),
            array("id"=>"1506","provinsi_id"=>"15","kabupaten"=>"KABUPATEN TANJUNG JABUNG TIMUR"),
            array("id"=>"1507","provinsi_id"=>"15","kabupaten"=>"KABUPATEN TANJUNG JABUNG BARAT"),
            array("id"=>"1508","provinsi_id"=>"15","kabupaten"=>"KABUPATEN TEBO"),
            array("id"=>"1509","provinsi_id"=>"15","kabupaten"=>"KABUPATEN BUNGO"),
            array("id"=>"1571","provinsi_id"=>"15","kabupaten"=>"KOTA JAMBI"),
            array("id"=>"1572","provinsi_id"=>"15","kabupaten"=>"KOTA SUNGAI PENUH"),
            array("id"=>"1601","provinsi_id"=>"16","kabupaten"=>"KABUPATEN OGAN KOMERING ULU"),
            array("id"=>"1602","provinsi_id"=>"16","kabupaten"=>"KABUPATEN OGAN KOMERING ILIR"),
            array("id"=>"1603","provinsi_id"=>"16","kabupaten"=>"KABUPATEN MUARA ENIM"),
            array("id"=>"1604","provinsi_id"=>"16","kabupaten"=>"KABUPATEN LAHAT"),
            array("id"=>"1605","provinsi_id"=>"16","kabupaten"=>"KABUPATEN MUSI RAWAS"),
            array("id"=>"1606","provinsi_id"=>"16","kabupaten"=>"KABUPATEN MUSI BANYUASIN"),
            array("id"=>"1607","provinsi_id"=>"16","kabupaten"=>"KABUPATEN BANYU ASIN"),
            array("id"=>"1608","provinsi_id"=>"16","kabupaten"=>"KABUPATEN OGAN KOMERING ULU SELATAN"),
            array("id"=>"1609","provinsi_id"=>"16","kabupaten"=>"KABUPATEN OGAN KOMERING ULU TIMUR"),
            array("id"=>"1610","provinsi_id"=>"16","kabupaten"=>"KABUPATEN OGAN ILIR"),
            array("id"=>"1611","provinsi_id"=>"16","kabupaten"=>"KABUPATEN EMPAT LAWANG"),
            array("id"=>"1612","provinsi_id"=>"16","kabupaten"=>"KABUPATEN PENUKAL ABAB LEMATANG ILIR"),
            array("id"=>"1613","provinsi_id"=>"16","kabupaten"=>"KABUPATEN MUSI RAWAS UTARA"),
            array("id"=>"1671","provinsi_id"=>"16","kabupaten"=>"KOTA PALEMBANG"),
            array("id"=>"1672","provinsi_id"=>"16","kabupaten"=>"KOTA PRABUMULIH"),
            array("id"=>"1673","provinsi_id"=>"16","kabupaten"=>"KOTA PAGAR ALAM"),
            array("id"=>"1674","provinsi_id"=>"16","kabupaten"=>"KOTA LUBUKLINGGAU"),
            array("id"=>"1701","provinsi_id"=>"17","kabupaten"=>"KABUPATEN BENGKULU SELATAN"),
            array("id"=>"1702","provinsi_id"=>"17","kabupaten"=>"KABUPATEN REJANG LEBONG"),
            array("id"=>"1703","provinsi_id"=>"17","kabupaten"=>"KABUPATEN BENGKULU UTARA"),
            array("id"=>"1704","provinsi_id"=>"17","kabupaten"=>"KABUPATEN KAUR"),
            array("id"=>"1705","provinsi_id"=>"17","kabupaten"=>"KABUPATEN SELUMA"),
            array("id"=>"1706","provinsi_id"=>"17","kabupaten"=>"KABUPATEN MUKOMUKO"),
            array("id"=>"1707","provinsi_id"=>"17","kabupaten"=>"KABUPATEN LEBONG"),
            array("id"=>"1708","provinsi_id"=>"17","kabupaten"=>"KABUPATEN KEPAHIANG"),
            array("id"=>"1709","provinsi_id"=>"17","kabupaten"=>"KABUPATEN BENGKULU TENGAH"),
            array("id"=>"1771","provinsi_id"=>"17","kabupaten"=>"KOTA BENGKULU"),
            array("id"=>"1801","provinsi_id"=>"18","kabupaten"=>"KABUPATEN LAMPUNG BARAT"),
            array("id"=>"1802","provinsi_id"=>"18","kabupaten"=>"KABUPATEN TANGGAMUS"),
            array("id"=>"1803","provinsi_id"=>"18","kabupaten"=>"KABUPATEN LAMPUNG SELATAN"),
            array("id"=>"1804","provinsi_id"=>"18","kabupaten"=>"KABUPATEN LAMPUNG TIMUR"),
            array("id"=>"1805","provinsi_id"=>"18","kabupaten"=>"KABUPATEN LAMPUNG TENGAH"),
            array("id"=>"1806","provinsi_id"=>"18","kabupaten"=>"KABUPATEN LAMPUNG UTARA"),
            array("id"=>"1807","provinsi_id"=>"18","kabupaten"=>"KABUPATEN WAY KANAN"),
            array("id"=>"1808","provinsi_id"=>"18","kabupaten"=>"KABUPATEN TULANGBAWANG"),
            array("id"=>"1809","provinsi_id"=>"18","kabupaten"=>"KABUPATEN PESAWARAN"),
            array("id"=>"1810","provinsi_id"=>"18","kabupaten"=>"KABUPATEN PRINGSEWU"),
            array("id"=>"1811","provinsi_id"=>"18","kabupaten"=>"KABUPATEN MESUJI"),
            array("id"=>"1812","provinsi_id"=>"18","kabupaten"=>"KABUPATEN TULANG BAWANG BARAT"),
            array("id"=>"1813","provinsi_id"=>"18","kabupaten"=>"KABUPATEN PESISIR BARAT"),
            array("id"=>"1871","provinsi_id"=>"18","kabupaten"=>"KOTA BANDAR LAMPUNG"),
            array("id"=>"1872","provinsi_id"=>"18","kabupaten"=>"KOTA METRO"),
            array("id"=>"1901","provinsi_id"=>"19","kabupaten"=>"KABUPATEN BANGKA"),
            array("id"=>"1902","provinsi_id"=>"19","kabupaten"=>"KABUPATEN BELITUNG"),
            array("id"=>"1903","provinsi_id"=>"19","kabupaten"=>"KABUPATEN BANGKA BARAT"),
            array("id"=>"1904","provinsi_id"=>"19","kabupaten"=>"KABUPATEN BANGKA TENGAH"),
            array("id"=>"1905","provinsi_id"=>"19","kabupaten"=>"KABUPATEN BANGKA SELATAN"),
            array("id"=>"1906","provinsi_id"=>"19","kabupaten"=>"KABUPATEN BELITUNG TIMUR"),
            array("id"=>"1971","provinsi_id"=>"19","kabupaten"=>"KOTA PANGKAL PINANG"),
            array("id"=>"2101","provinsi_id"=>"21","kabupaten"=>"KABUPATEN KARIMUN"),
            array("id"=>"2102","provinsi_id"=>"21","kabupaten"=>"KABUPATEN BINTAN"),
            array("id"=>"2103","provinsi_id"=>"21","kabupaten"=>"KABUPATEN NATUNA"),
            array("id"=>"2104","provinsi_id"=>"21","kabupaten"=>"KABUPATEN LINGGA"),
            array("id"=>"2105","provinsi_id"=>"21","kabupaten"=>"KABUPATEN KEPULAUAN ANAMBAS"),
            array("id"=>"2171","provinsi_id"=>"21","kabupaten"=>"KOTA B A T A M"),
            array("id"=>"2172","provinsi_id"=>"21","kabupaten"=>"KOTA TANJUNG PINANG"),
            array("id"=>"3101","provinsi_id"=>"31","kabupaten"=>"KABUPATEN KEPULAUAN SERIBU"),
            array("id"=>"3171","provinsi_id"=>"31","kabupaten"=>"KOTA JAKARTA SELATAN"),
            array("id"=>"3172","provinsi_id"=>"31","kabupaten"=>"KOTA JAKARTA TIMUR"),
            array("id"=>"3173","provinsi_id"=>"31","kabupaten"=>"KOTA JAKARTA PUSAT"),
            array("id"=>"3174","provinsi_id"=>"31","kabupaten"=>"KOTA JAKARTA BARAT"),
            array("id"=>"3175","provinsi_id"=>"31","kabupaten"=>"KOTA JAKARTA UTARA"),
            array("id"=>"3201","provinsi_id"=>"32","kabupaten"=>"KABUPATEN BOGOR"),
            array("id"=>"3202","provinsi_id"=>"32","kabupaten"=>"KABUPATEN SUKABUMI"),
            array("id"=>"3203","provinsi_id"=>"32","kabupaten"=>"KABUPATEN CIANJUR"),
            array("id"=>"3204","provinsi_id"=>"32","kabupaten"=>"KABUPATEN BANDUNG"),
            array("id"=>"3205","provinsi_id"=>"32","kabupaten"=>"KABUPATEN GARUT"),
            array("id"=>"3206","provinsi_id"=>"32","kabupaten"=>"KABUPATEN TASIKMALAYA"),
            array("id"=>"3207","provinsi_id"=>"32","kabupaten"=>"KABUPATEN CIAMIS"),
            array("id"=>"3208","provinsi_id"=>"32","kabupaten"=>"KABUPATEN KUNINGAN"),
            array("id"=>"3209","provinsi_id"=>"32","kabupaten"=>"KABUPATEN CIREBON"),
            array("id"=>"3210","provinsi_id"=>"32","kabupaten"=>"KABUPATEN MAJALENGKA"),
            array("id"=>"3211","provinsi_id"=>"32","kabupaten"=>"KABUPATEN SUMEDANG"),
            array("id"=>"3212","provinsi_id"=>"32","kabupaten"=>"KABUPATEN INDRAMAYU"),
            array("id"=>"3213","provinsi_id"=>"32","kabupaten"=>"KABUPATEN SUBANG"),
            array("id"=>"3214","provinsi_id"=>"32","kabupaten"=>"KABUPATEN PURWAKARTA"),
            array("id"=>"3215","provinsi_id"=>"32","kabupaten"=>"KABUPATEN KARAWANG"),
            array("id"=>"3216","provinsi_id"=>"32","kabupaten"=>"KABUPATEN BEKASI"),
            array("id"=>"3217","provinsi_id"=>"32","kabupaten"=>"KABUPATEN BANDUNG BARAT"),
            array("id"=>"3218","provinsi_id"=>"32","kabupaten"=>"KABUPATEN PANGANDARAN"),
            array("id"=>"3271","provinsi_id"=>"32","kabupaten"=>"KOTA BOGOR"),
            array("id"=>"3272","provinsi_id"=>"32","kabupaten"=>"KOTA SUKABUMI"),
            array("id"=>"3273","provinsi_id"=>"32","kabupaten"=>"KOTA BANDUNG"),
            array("id"=>"3274","provinsi_id"=>"32","kabupaten"=>"KOTA CIREBON"),
            array("id"=>"3275","provinsi_id"=>"32","kabupaten"=>"KOTA BEKASI"),
            array("id"=>"3276","provinsi_id"=>"32","kabupaten"=>"KOTA DEPOK"),
            array("id"=>"3277","provinsi_id"=>"32","kabupaten"=>"KOTA CIMAHI"),
            array("id"=>"3278","provinsi_id"=>"32","kabupaten"=>"KOTA TASIKMALAYA"),
            array("id"=>"3279","provinsi_id"=>"32","kabupaten"=>"KOTA BANJAR"),
            array("id"=>"3301","provinsi_id"=>"33","kabupaten"=>"KABUPATEN CILACAP"),
            array("id"=>"3302","provinsi_id"=>"33","kabupaten"=>"KABUPATEN BANYUMAS"),
            array("id"=>"3303","provinsi_id"=>"33","kabupaten"=>"KABUPATEN PURBALINGGA"),
            array("id"=>"3304","provinsi_id"=>"33","kabupaten"=>"KABUPATEN BANJARNEGARA"),
            array("id"=>"3305","provinsi_id"=>"33","kabupaten"=>"KABUPATEN KEBUMEN"),
            array("id"=>"3306","provinsi_id"=>"33","kabupaten"=>"KABUPATEN PURWOREJO"),
            array("id"=>"3307","provinsi_id"=>"33","kabupaten"=>"KABUPATEN WONOSOBO"),
            array("id"=>"3308","provinsi_id"=>"33","kabupaten"=>"KABUPATEN MAGELANG"),
            array("id"=>"3309","provinsi_id"=>"33","kabupaten"=>"KABUPATEN BOYOLALI"),
            array("id"=>"3310","provinsi_id"=>"33","kabupaten"=>"KABUPATEN KLATEN"),
            array("id"=>"3311","provinsi_id"=>"33","kabupaten"=>"KABUPATEN SUKOHARJO"),
            array("id"=>"3312","provinsi_id"=>"33","kabupaten"=>"KABUPATEN WONOGIRI"),
            array("id"=>"3313","provinsi_id"=>"33","kabupaten"=>"KABUPATEN KARANGANYAR"),
            array("id"=>"3314","provinsi_id"=>"33","kabupaten"=>"KABUPATEN SRAGEN"),
            array("id"=>"3315","provinsi_id"=>"33","kabupaten"=>"KABUPATEN GROBOGAN"),
            array("id"=>"3316","provinsi_id"=>"33","kabupaten"=>"KABUPATEN BLORA"),
            array("id"=>"3317","provinsi_id"=>"33","kabupaten"=>"KABUPATEN REMBANG"),
            array("id"=>"3318","provinsi_id"=>"33","kabupaten"=>"KABUPATEN PATI"),
            array("id"=>"3319","provinsi_id"=>"33","kabupaten"=>"KABUPATEN KUDUS"),
            array("id"=>"3320","provinsi_id"=>"33","kabupaten"=>"KABUPATEN JEPARA"),
            array("id"=>"3321","provinsi_id"=>"33","kabupaten"=>"KABUPATEN DEMAK"),
            array("id"=>"3322","provinsi_id"=>"33","kabupaten"=>"KABUPATEN SEMARANG"),
            array("id"=>"3323","provinsi_id"=>"33","kabupaten"=>"KABUPATEN TEMANGGUNG"),
            array("id"=>"3324","provinsi_id"=>"33","kabupaten"=>"KABUPATEN KENDAL"),
            array("id"=>"3325","provinsi_id"=>"33","kabupaten"=>"KABUPATEN BATANG"),
            array("id"=>"3326","provinsi_id"=>"33","kabupaten"=>"KABUPATEN PEKALONGAN"),
            array("id"=>"3327","provinsi_id"=>"33","kabupaten"=>"KABUPATEN PEMALANG"),
            array("id"=>"3328","provinsi_id"=>"33","kabupaten"=>"KABUPATEN TEGAL"),
            array("id"=>"3329","provinsi_id"=>"33","kabupaten"=>"KABUPATEN BREBES"),
            array("id"=>"3371","provinsi_id"=>"33","kabupaten"=>"KOTA MAGELANG"),
            array("id"=>"3372","provinsi_id"=>"33","kabupaten"=>"KOTA SURAKARTA"),
            array("id"=>"3373","provinsi_id"=>"33","kabupaten"=>"KOTA SALATIGA"),
            array("id"=>"3374","provinsi_id"=>"33","kabupaten"=>"KOTA SEMARANG"),
            array("id"=>"3375","provinsi_id"=>"33","kabupaten"=>"KOTA PEKALONGAN"),
            array("id"=>"3376","provinsi_id"=>"33","kabupaten"=>"KOTA TEGAL"),
            array("id"=>"3401","provinsi_id"=>"34","kabupaten"=>"KABUPATEN KULON PROGO"),
            array("id"=>"3402","provinsi_id"=>"34","kabupaten"=>"KABUPATEN BANTUL"),
            array("id"=>"3403","provinsi_id"=>"34","kabupaten"=>"KABUPATEN GUNUNG KIDUL"),
            array("id"=>"3404","provinsi_id"=>"34","kabupaten"=>"KABUPATEN SLEMAN"),
            array("id"=>"3471","provinsi_id"=>"34","kabupaten"=>"KOTA YOGYAKARTA"),
            array("id"=>"3501","provinsi_id"=>"35","kabupaten"=>"KABUPATEN PACITAN"),
            array("id"=>"3502","provinsi_id"=>"35","kabupaten"=>"KABUPATEN PONOROGO"),
            array("id"=>"3503","provinsi_id"=>"35","kabupaten"=>"KABUPATEN TRENGGALEK"),
            array("id"=>"3504","provinsi_id"=>"35","kabupaten"=>"KABUPATEN TULUNGAGUNG"),
            array("id"=>"3505","provinsi_id"=>"35","kabupaten"=>"KABUPATEN BLITAR"),
            array("id"=>"3506","provinsi_id"=>"35","kabupaten"=>"KABUPATEN KEDIRI"),
            array("id"=>"3507","provinsi_id"=>"35","kabupaten"=>"KABUPATEN MALANG"),
            array("id"=>"3508","provinsi_id"=>"35","kabupaten"=>"KABUPATEN LUMAJANG"),
            array("id"=>"3509","provinsi_id"=>"35","kabupaten"=>"KABUPATEN JEMBER"),
            array("id"=>"3510","provinsi_id"=>"35","kabupaten"=>"KABUPATEN BANYUWANGI"),
            array("id"=>"3511","provinsi_id"=>"35","kabupaten"=>"KABUPATEN BONDOWOSO"),
            array("id"=>"3512","provinsi_id"=>"35","kabupaten"=>"KABUPATEN SITUBONDO"),
            array("id"=>"3513","provinsi_id"=>"35","kabupaten"=>"KABUPATEN PROBOLINGGO"),
            array("id"=>"3514","provinsi_id"=>"35","kabupaten"=>"KABUPATEN PASURUAN"),
            array("id"=>"3515","provinsi_id"=>"35","kabupaten"=>"KABUPATEN SIDOARJO"),
            array("id"=>"3516","provinsi_id"=>"35","kabupaten"=>"KABUPATEN MOJOKERTO"),
            array("id"=>"3517","provinsi_id"=>"35","kabupaten"=>"KABUPATEN JOMBANG"),
            array("id"=>"3518","provinsi_id"=>"35","kabupaten"=>"KABUPATEN NGANJUK"),
            array("id"=>"3519","provinsi_id"=>"35","kabupaten"=>"KABUPATEN MADIUN"),
            array("id"=>"3520","provinsi_id"=>"35","kabupaten"=>"KABUPATEN MAGETAN"),
            array("id"=>"3521","provinsi_id"=>"35","kabupaten"=>"KABUPATEN NGAWI"),
            array("id"=>"3522","provinsi_id"=>"35","kabupaten"=>"KABUPATEN BOJONEGORO"),
            array("id"=>"3523","provinsi_id"=>"35","kabupaten"=>"KABUPATEN TUBAN"),
            array("id"=>"3524","provinsi_id"=>"35","kabupaten"=>"KABUPATEN LAMONGAN"),
            array("id"=>"3525","provinsi_id"=>"35","kabupaten"=>"KABUPATEN GRESIK"),
            array("id"=>"3526","provinsi_id"=>"35","kabupaten"=>"KABUPATEN BANGKALAN"),
            array("id"=>"3527","provinsi_id"=>"35","kabupaten"=>"KABUPATEN SAMPANG"),
            array("id"=>"3528","provinsi_id"=>"35","kabupaten"=>"KABUPATEN PAMEKASAN"),
            array("id"=>"3529","provinsi_id"=>"35","kabupaten"=>"KABUPATEN SUMENEP"),
            array("id"=>"3571","provinsi_id"=>"35","kabupaten"=>"KOTA KEDIRI"),
            array("id"=>"3572","provinsi_id"=>"35","kabupaten"=>"KOTA BLITAR"),
            array("id"=>"3573","provinsi_id"=>"35","kabupaten"=>"KOTA MALANG"),
            array("id"=>"3574","provinsi_id"=>"35","kabupaten"=>"KOTA PROBOLINGGO"),
            array("id"=>"3575","provinsi_id"=>"35","kabupaten"=>"KOTA PASURUAN"),
            array("id"=>"3576","provinsi_id"=>"35","kabupaten"=>"KOTA MOJOKERTO"),
            array("id"=>"3577","provinsi_id"=>"35","kabupaten"=>"KOTA MADIUN"),
            array("id"=>"3578","provinsi_id"=>"35","kabupaten"=>"KOTA SURABAYA"),
            array("id"=>"3579","provinsi_id"=>"35","kabupaten"=>"KOTA BATU"),
            array("id"=>"3601","provinsi_id"=>"36","kabupaten"=>"KABUPATEN PANDEGLANG"),
            array("id"=>"3602","provinsi_id"=>"36","kabupaten"=>"KABUPATEN LEBAK"),
            array("id"=>"3603","provinsi_id"=>"36","kabupaten"=>"KABUPATEN TANGERANG"),
            array("id"=>"3604","provinsi_id"=>"36","kabupaten"=>"KABUPATEN SERANG"),
            array("id"=>"3671","provinsi_id"=>"36","kabupaten"=>"KOTA TANGERANG"),
            array("id"=>"3672","provinsi_id"=>"36","kabupaten"=>"KOTA CILEGON"),
            array("id"=>"3673","provinsi_id"=>"36","kabupaten"=>"KOTA SERANG"),
            array("id"=>"3674","provinsi_id"=>"36","kabupaten"=>"KOTA TANGERANG SELATAN"),
            array("id"=>"5101","provinsi_id"=>"51","kabupaten"=>"KABUPATEN JEMBRANA"),
            array("id"=>"5102","provinsi_id"=>"51","kabupaten"=>"KABUPATEN TABANAN"),
            array("id"=>"5103","provinsi_id"=>"51","kabupaten"=>"KABUPATEN BADUNG"),
            array("id"=>"5104","provinsi_id"=>"51","kabupaten"=>"KABUPATEN GIANYAR"),
            array("id"=>"5105","provinsi_id"=>"51","kabupaten"=>"KABUPATEN KLUNGKUNG"),
            array("id"=>"5106","provinsi_id"=>"51","kabupaten"=>"KABUPATEN BANGLI"),
            array("id"=>"5107","provinsi_id"=>"51","kabupaten"=>"KABUPATEN KARANG ASEM"),
            array("id"=>"5108","provinsi_id"=>"51","kabupaten"=>"KABUPATEN BULELENG"),
            array("id"=>"5171","provinsi_id"=>"51","kabupaten"=>"KOTA DENPASAR"),
            array("id"=>"5201","provinsi_id"=>"52","kabupaten"=>"KABUPATEN LOMBOK BARAT"),
            array("id"=>"5202","provinsi_id"=>"52","kabupaten"=>"KABUPATEN LOMBOK TENGAH"),
            array("id"=>"5203","provinsi_id"=>"52","kabupaten"=>"KABUPATEN LOMBOK TIMUR"),
            array("id"=>"5204","provinsi_id"=>"52","kabupaten"=>"KABUPATEN SUMBAWA"),
            array("id"=>"5205","provinsi_id"=>"52","kabupaten"=>"KABUPATEN DOMPU"),
            array("id"=>"5206","provinsi_id"=>"52","kabupaten"=>"KABUPATEN BIMA"),
            array("id"=>"5207","provinsi_id"=>"52","kabupaten"=>"KABUPATEN SUMBAWA BARAT"),
            array("id"=>"5208","provinsi_id"=>"52","kabupaten"=>"KABUPATEN LOMBOK UTARA"),
            array("id"=>"5271","provinsi_id"=>"52","kabupaten"=>"KOTA MATARAM"),
            array("id"=>"5272","provinsi_id"=>"52","kabupaten"=>"KOTA BIMA"),
            array("id"=>"5301","provinsi_id"=>"53","kabupaten"=>"KABUPATEN SUMBA BARAT"),
            array("id"=>"5302","provinsi_id"=>"53","kabupaten"=>"KABUPATEN SUMBA TIMUR"),
            array("id"=>"5303","provinsi_id"=>"53","kabupaten"=>"KABUPATEN KUPANG"),
            array("id"=>"5304","provinsi_id"=>"53","kabupaten"=>"KABUPATEN TIMOR TENGAH SELATAN"),
            array("id"=>"5305","provinsi_id"=>"53","kabupaten"=>"KABUPATEN TIMOR TENGAH UTARA"),
            array("id"=>"5306","provinsi_id"=>"53","kabupaten"=>"KABUPATEN BELU"),
            array("id"=>"5307","provinsi_id"=>"53","kabupaten"=>"KABUPATEN ALOR"),
            array("id"=>"5308","provinsi_id"=>"53","kabupaten"=>"KABUPATEN LEMBATA"),
            array("id"=>"5309","provinsi_id"=>"53","kabupaten"=>"KABUPATEN FLORES TIMUR"),
            array("id"=>"5310","provinsi_id"=>"53","kabupaten"=>"KABUPATEN SIKKA"),
            array("id"=>"5311","provinsi_id"=>"53","kabupaten"=>"KABUPATEN ENDE"),
            array("id"=>"5312","provinsi_id"=>"53","kabupaten"=>"KABUPATEN NGADA"),
            array("id"=>"5313","provinsi_id"=>"53","kabupaten"=>"KABUPATEN MANGGARAI"),
            array("id"=>"5314","provinsi_id"=>"53","kabupaten"=>"KABUPATEN ROTE NDAO"),
            array("id"=>"5315","provinsi_id"=>"53","kabupaten"=>"KABUPATEN MANGGARAI BARAT"),
            array("id"=>"5316","provinsi_id"=>"53","kabupaten"=>"KABUPATEN SUMBA TENGAH"),
            array("id"=>"5317","provinsi_id"=>"53","kabupaten"=>"KABUPATEN SUMBA BARAT DAYA"),
            array("id"=>"5318","provinsi_id"=>"53","kabupaten"=>"KABUPATEN NAGEKEO"),
            array("id"=>"5319","provinsi_id"=>"53","kabupaten"=>"KABUPATEN MANGGARAI TIMUR"),
            array("id"=>"5320","provinsi_id"=>"53","kabupaten"=>"KABUPATEN SABU RAIJUA"),
            array("id"=>"5321","provinsi_id"=>"53","kabupaten"=>"KABUPATEN MALAKA"),
            array("id"=>"5371","provinsi_id"=>"53","kabupaten"=>"KOTA KUPANG"),
            array("id"=>"6101","provinsi_id"=>"61","kabupaten"=>"KABUPATEN SAMBAS"),
            array("id"=>"6102","provinsi_id"=>"61","kabupaten"=>"KABUPATEN BENGKAYANG"),
            array("id"=>"6103","provinsi_id"=>"61","kabupaten"=>"KABUPATEN LANDAK"),
            array("id"=>"6104","provinsi_id"=>"61","kabupaten"=>"KABUPATEN MEMPAWAH"),
            array("id"=>"6105","provinsi_id"=>"61","kabupaten"=>"KABUPATEN SANGGAU"),
            array("id"=>"6106","provinsi_id"=>"61","kabupaten"=>"KABUPATEN KETAPANG"),
            array("id"=>"6107","provinsi_id"=>"61","kabupaten"=>"KABUPATEN SINTANG"),
            array("id"=>"6108","provinsi_id"=>"61","kabupaten"=>"KABUPATEN KAPUAS HULU"),
            array("id"=>"6109","provinsi_id"=>"61","kabupaten"=>"KABUPATEN SEKADAU"),
            array("id"=>"6110","provinsi_id"=>"61","kabupaten"=>"KABUPATEN MELAWI"),
            array("id"=>"6111","provinsi_id"=>"61","kabupaten"=>"KABUPATEN KAYONG UTARA"),
            array("id"=>"6112","provinsi_id"=>"61","kabupaten"=>"KABUPATEN KUBU RAYA"),
            array("id"=>"6171","provinsi_id"=>"61","kabupaten"=>"KOTA PONTIANAK"),
            array("id"=>"6172","provinsi_id"=>"61","kabupaten"=>"KOTA SINGKAWANG"),
            array("id"=>"6201","provinsi_id"=>"62","kabupaten"=>"KABUPATEN KOTAWARINGIN BARAT"),
            array("id"=>"6202","provinsi_id"=>"62","kabupaten"=>"KABUPATEN KOTAWARINGIN TIMUR"),
            array("id"=>"6203","provinsi_id"=>"62","kabupaten"=>"KABUPATEN KAPUAS"),
            array("id"=>"6204","provinsi_id"=>"62","kabupaten"=>"KABUPATEN BARITO SELATAN"),
            array("id"=>"6205","provinsi_id"=>"62","kabupaten"=>"KABUPATEN BARITO UTARA"),
            array("id"=>"6206","provinsi_id"=>"62","kabupaten"=>"KABUPATEN SUKAMARA"),
            array("id"=>"6207","provinsi_id"=>"62","kabupaten"=>"KABUPATEN LAMANDAU"),
            array("id"=>"6208","provinsi_id"=>"62","kabupaten"=>"KABUPATEN SERUYAN"),
            array("id"=>"6209","provinsi_id"=>"62","kabupaten"=>"KABUPATEN KATINGAN"),
            array("id"=>"6210","provinsi_id"=>"62","kabupaten"=>"KABUPATEN PULANG PISAU"),
            array("id"=>"6211","provinsi_id"=>"62","kabupaten"=>"KABUPATEN GUNUNG MAS"),
            array("id"=>"6212","provinsi_id"=>"62","kabupaten"=>"KABUPATEN BARITO TIMUR"),
            array("id"=>"6213","provinsi_id"=>"62","kabupaten"=>"KABUPATEN MURUNG RAYA"),
            array("id"=>"6271","provinsi_id"=>"62","kabupaten"=>"KOTA PALANGKA RAYA"),
            array("id"=>"6301","provinsi_id"=>"63","kabupaten"=>"KABUPATEN TANAH LAUT"),
            array("id"=>"6302","provinsi_id"=>"63","kabupaten"=>"KABUPATEN KOTA BARU"),
            array("id"=>"6303","provinsi_id"=>"63","kabupaten"=>"KABUPATEN BANJAR"),
            array("id"=>"6304","provinsi_id"=>"63","kabupaten"=>"KABUPATEN BARITO KUALA"),
            array("id"=>"6305","provinsi_id"=>"63","kabupaten"=>"KABUPATEN TAPIN"),
            array("id"=>"6306","provinsi_id"=>"63","kabupaten"=>"KABUPATEN HULU SUNGAI SELATAN"),
            array("id"=>"6307","provinsi_id"=>"63","kabupaten"=>"KABUPATEN HULU SUNGAI TENGAH"),
            array("id"=>"6308","provinsi_id"=>"63","kabupaten"=>"KABUPATEN HULU SUNGAI UTARA"),
            array("id"=>"6309","provinsi_id"=>"63","kabupaten"=>"KABUPATEN TABALONG"),
            array("id"=>"6310","provinsi_id"=>"63","kabupaten"=>"KABUPATEN TANAH BUMBU"),
            array("id"=>"6311","provinsi_id"=>"63","kabupaten"=>"KABUPATEN BALANGAN"),
            array("id"=>"6371","provinsi_id"=>"63","kabupaten"=>"KOTA BANJARMASIN"),
            array("id"=>"6372","provinsi_id"=>"63","kabupaten"=>"KOTA BANJAR BARU"),
            array("id"=>"6401","provinsi_id"=>"64","kabupaten"=>"KABUPATEN PASER"),
            array("id"=>"6402","provinsi_id"=>"64","kabupaten"=>"KABUPATEN KUTAI BARAT"),
            array("id"=>"6403","provinsi_id"=>"64","kabupaten"=>"KABUPATEN KUTAI KARTANEGARA"),
            array("id"=>"6404","provinsi_id"=>"64","kabupaten"=>"KABUPATEN KUTAI TIMUR"),
            array("id"=>"6405","provinsi_id"=>"64","kabupaten"=>"KABUPATEN BERAU"),
            array("id"=>"6409","provinsi_id"=>"64","kabupaten"=>"KABUPATEN PENAJAM PASER UTARA"),
            array("id"=>"6411","provinsi_id"=>"64","kabupaten"=>"KABUPATEN MAHAKAM HULU"),
            array("id"=>"6471","provinsi_id"=>"64","kabupaten"=>"KOTA BALIKPAPAN"),
            array("id"=>"6472","provinsi_id"=>"64","kabupaten"=>"KOTA SAMARINDA"),
            array("id"=>"6474","provinsi_id"=>"64","kabupaten"=>"KOTA BONTANG"),
            array("id"=>"6501","provinsi_id"=>"65","kabupaten"=>"KABUPATEN MALINAU"),
            array("id"=>"6502","provinsi_id"=>"65","kabupaten"=>"KABUPATEN BULUNGAN"),
            array("id"=>"6503","provinsi_id"=>"65","kabupaten"=>"KABUPATEN TANA TIDUNG"),
            array("id"=>"6504","provinsi_id"=>"65","kabupaten"=>"KABUPATEN NUNUKAN"),
            array("id"=>"6571","provinsi_id"=>"65","kabupaten"=>"KOTA TARAKAN"),
            array("id"=>"7101","provinsi_id"=>"71","kabupaten"=>"KABUPATEN BOLAANG MONGONDOW"),
            array("id"=>"7102","provinsi_id"=>"71","kabupaten"=>"KABUPATEN MINAHASA"),
            array("id"=>"7103","provinsi_id"=>"71","kabupaten"=>"KABUPATEN KEPULAUAN SANGIHE"),
            array("id"=>"7104","provinsi_id"=>"71","kabupaten"=>"KABUPATEN KEPULAUAN TALAUD"),
            array("id"=>"7105","provinsi_id"=>"71","kabupaten"=>"KABUPATEN MINAHASA SELATAN"),
            array("id"=>"7106","provinsi_id"=>"71","kabupaten"=>"KABUPATEN MINAHASA UTARA"),
            array("id"=>"7107","provinsi_id"=>"71","kabupaten"=>"KABUPATEN BOLAANG MONGONDOW UTARA"),
            array("id"=>"7108","provinsi_id"=>"71","kabupaten"=>"KABUPATEN SIAU TAGULANDANG BIARO"),
            array("id"=>"7109","provinsi_id"=>"71","kabupaten"=>"KABUPATEN MINAHASA TENGGARA"),
            array("id"=>"7110","provinsi_id"=>"71","kabupaten"=>"KABUPATEN BOLAANG MONGONDOW SELATAN"),
            array("id"=>"7111","provinsi_id"=>"71","kabupaten"=>"KABUPATEN BOLAANG MONGONDOW TIMUR"),
            array("id"=>"7171","provinsi_id"=>"71","kabupaten"=>"KOTA MANADO"),
            array("id"=>"7172","provinsi_id"=>"71","kabupaten"=>"KOTA BITUNG"),
            array("id"=>"7173","provinsi_id"=>"71","kabupaten"=>"KOTA TOMOHON"),
            array("id"=>"7174","provinsi_id"=>"71","kabupaten"=>"KOTA KOTAMOBAGU"),
            array("id"=>"7201","provinsi_id"=>"72","kabupaten"=>"KABUPATEN BANGGAI KEPULAUAN"),
            array("id"=>"7202","provinsi_id"=>"72","kabupaten"=>"KABUPATEN BANGGAI"),
            array("id"=>"7203","provinsi_id"=>"72","kabupaten"=>"KABUPATEN MOROWALI"),
            array("id"=>"7204","provinsi_id"=>"72","kabupaten"=>"KABUPATEN POSO"),
            array("id"=>"7205","provinsi_id"=>"72","kabupaten"=>"KABUPATEN DONGGALA"),
            array("id"=>"7206","provinsi_id"=>"72","kabupaten"=>"KABUPATEN TOLI-TOLI"),
            array("id"=>"7207","provinsi_id"=>"72","kabupaten"=>"KABUPATEN BUOL"),
            array("id"=>"7208","provinsi_id"=>"72","kabupaten"=>"KABUPATEN PARIGI MOUTONG"),
            array("id"=>"7209","provinsi_id"=>"72","kabupaten"=>"KABUPATEN TOJO UNA-UNA"),
            array("id"=>"7210","provinsi_id"=>"72","kabupaten"=>"KABUPATEN SIGI"),
            array("id"=>"7211","provinsi_id"=>"72","kabupaten"=>"KABUPATEN BANGGAI LAUT"),
            array("id"=>"7212","provinsi_id"=>"72","kabupaten"=>"KABUPATEN MOROWALI UTARA"),
            array("id"=>"7271","provinsi_id"=>"72","kabupaten"=>"KOTA PALU"),
            array("id"=>"7301","provinsi_id"=>"73","kabupaten"=>"KABUPATEN KEPULAUAN SELAYAR"),
            array("id"=>"7302","provinsi_id"=>"73","kabupaten"=>"KABUPATEN BULUKUMBA"),
            array("id"=>"7303","provinsi_id"=>"73","kabupaten"=>"KABUPATEN BANTAENG"),
            array("id"=>"7304","provinsi_id"=>"73","kabupaten"=>"KABUPATEN JENEPONTO"),
            array("id"=>"7305","provinsi_id"=>"73","kabupaten"=>"KABUPATEN TAKALAR"),
            array("id"=>"7306","provinsi_id"=>"73","kabupaten"=>"KABUPATEN GOWA"),
            array("id"=>"7307","provinsi_id"=>"73","kabupaten"=>"KABUPATEN SINJAI"),
            array("id"=>"7308","provinsi_id"=>"73","kabupaten"=>"KABUPATEN MAROS"),
            array("id"=>"7309","provinsi_id"=>"73","kabupaten"=>"KABUPATEN PANGKAJENE DAN KEPULAUAN"),
            array("id"=>"7310","provinsi_id"=>"73","kabupaten"=>"KABUPATEN BARRU"),
            array("id"=>"7311","provinsi_id"=>"73","kabupaten"=>"KABUPATEN BONE"),
            array("id"=>"7312","provinsi_id"=>"73","kabupaten"=>"KABUPATEN SOPPENG"),
            array("id"=>"7313","provinsi_id"=>"73","kabupaten"=>"KABUPATEN WAJO"),
            array("id"=>"7314","provinsi_id"=>"73","kabupaten"=>"KABUPATEN SIDENRENG RAPPANG"),
            array("id"=>"7315","provinsi_id"=>"73","kabupaten"=>"KABUPATEN PINRANG"),
            array("id"=>"7316","provinsi_id"=>"73","kabupaten"=>"KABUPATEN ENREKANG"),
            array("id"=>"7317","provinsi_id"=>"73","kabupaten"=>"KABUPATEN LUWU"),
            array("id"=>"7318","provinsi_id"=>"73","kabupaten"=>"KABUPATEN TANA TORAJA"),
            array("id"=>"7322","provinsi_id"=>"73","kabupaten"=>"KABUPATEN LUWU UTARA"),
            array("id"=>"7325","provinsi_id"=>"73","kabupaten"=>"KABUPATEN LUWU TIMUR"),
            array("id"=>"7326","provinsi_id"=>"73","kabupaten"=>"KABUPATEN TORAJA UTARA"),
            array("id"=>"7371","provinsi_id"=>"73","kabupaten"=>"KOTA MAKASSAR"),
            array("id"=>"7372","provinsi_id"=>"73","kabupaten"=>"KOTA PAREPARE"),
            array("id"=>"7373","provinsi_id"=>"73","kabupaten"=>"KOTA PALOPO"),
            array("id"=>"7401","provinsi_id"=>"74","kabupaten"=>"KABUPATEN BUTON"),
            array("id"=>"7402","provinsi_id"=>"74","kabupaten"=>"KABUPATEN MUNA"),
            array("id"=>"7403","provinsi_id"=>"74","kabupaten"=>"KABUPATEN KONAWE"),
            array("id"=>"7404","provinsi_id"=>"74","kabupaten"=>"KABUPATEN KOLAKA"),
            array("id"=>"7405","provinsi_id"=>"74","kabupaten"=>"KABUPATEN KONAWE SELATAN"),
            array("id"=>"7406","provinsi_id"=>"74","kabupaten"=>"KABUPATEN BOMBANA"),
            array("id"=>"7407","provinsi_id"=>"74","kabupaten"=>"KABUPATEN WAKATOBI"),
            array("id"=>"7408","provinsi_id"=>"74","kabupaten"=>"KABUPATEN KOLAKA UTARA"),
            array("id"=>"7409","provinsi_id"=>"74","kabupaten"=>"KABUPATEN BUTON UTARA"),
            array("id"=>"7410","provinsi_id"=>"74","kabupaten"=>"KABUPATEN KONAWE UTARA"),
            array("id"=>"7411","provinsi_id"=>"74","kabupaten"=>"KABUPATEN KOLAKA TIMUR"),
            array("id"=>"7412","provinsi_id"=>"74","kabupaten"=>"KABUPATEN KONAWE KEPULAUAN"),
            array("id"=>"7413","provinsi_id"=>"74","kabupaten"=>"KABUPATEN MUNA BARAT"),
            array("id"=>"7414","provinsi_id"=>"74","kabupaten"=>"KABUPATEN BUTON TENGAH"),
            array("id"=>"7415","provinsi_id"=>"74","kabupaten"=>"KABUPATEN BUTON SELATAN"),
            array("id"=>"7471","provinsi_id"=>"74","kabupaten"=>"KOTA KENDARI"),
            array("id"=>"7472","provinsi_id"=>"74","kabupaten"=>"KOTA BAUBAU"),
            array("id"=>"7501","provinsi_id"=>"75","kabupaten"=>"KABUPATEN BOALEMO"),
            array("id"=>"7502","provinsi_id"=>"75","kabupaten"=>"KABUPATEN GORONTALO"),
            array("id"=>"7503","provinsi_id"=>"75","kabupaten"=>"KABUPATEN POHUWATO"),
            array("id"=>"7504","provinsi_id"=>"75","kabupaten"=>"KABUPATEN BONE BOLANGO"),
            array("id"=>"7505","provinsi_id"=>"75","kabupaten"=>"KABUPATEN GORONTALO UTARA"),
            array("id"=>"7571","provinsi_id"=>"75","kabupaten"=>"KOTA GORONTALO"),
            array("id"=>"7601","provinsi_id"=>"76","kabupaten"=>"KABUPATEN MAJENE"),
            array("id"=>"7602","provinsi_id"=>"76","kabupaten"=>"KABUPATEN POLEWALI MANDAR"),
            array("id"=>"7603","provinsi_id"=>"76","kabupaten"=>"KABUPATEN MAMASA"),
            array("id"=>"7604","provinsi_id"=>"76","kabupaten"=>"KABUPATEN MAMUJU"),
            array("id"=>"7605","provinsi_id"=>"76","kabupaten"=>"KABUPATEN MAMUJU UTARA"),
            array("id"=>"7606","provinsi_id"=>"76","kabupaten"=>"KABUPATEN MAMUJU TENGAH"),
            array("id"=>"8101","provinsi_id"=>"81","kabupaten"=>"KABUPATEN MALUKU TENGGARA BARAT"),
            array("id"=>"8102","provinsi_id"=>"81","kabupaten"=>"KABUPATEN MALUKU TENGGARA"),
            array("id"=>"8103","provinsi_id"=>"81","kabupaten"=>"KABUPATEN MALUKU TENGAH"),
            array("id"=>"8104","provinsi_id"=>"81","kabupaten"=>"KABUPATEN BURU"),
            array("id"=>"8105","provinsi_id"=>"81","kabupaten"=>"KABUPATEN KEPULAUAN ARU"),
            array("id"=>"8106","provinsi_id"=>"81","kabupaten"=>"KABUPATEN SERAM BAGIAN BARAT"),
            array("id"=>"8107","provinsi_id"=>"81","kabupaten"=>"KABUPATEN SERAM BAGIAN TIMUR"),
            array("id"=>"8108","provinsi_id"=>"81","kabupaten"=>"KABUPATEN MALUKU BARAT DAYA"),
            array("id"=>"8109","provinsi_id"=>"81","kabupaten"=>"KABUPATEN BURU SELATAN"),
            array("id"=>"8171","provinsi_id"=>"81","kabupaten"=>"KOTA AMBON"),
            array("id"=>"8172","provinsi_id"=>"81","kabupaten"=>"KOTA TUAL"),
            array("id"=>"8201","provinsi_id"=>"82","kabupaten"=>"KABUPATEN HALMAHERA BARAT"),
            array("id"=>"8202","provinsi_id"=>"82","kabupaten"=>"KABUPATEN HALMAHERA TENGAH"),
            array("id"=>"8203","provinsi_id"=>"82","kabupaten"=>"KABUPATEN KEPULAUAN SULA"),
            array("id"=>"8204","provinsi_id"=>"82","kabupaten"=>"KABUPATEN HALMAHERA SELATAN"),
            array("id"=>"8205","provinsi_id"=>"82","kabupaten"=>"KABUPATEN HALMAHERA UTARA"),
            array("id"=>"8206","provinsi_id"=>"82","kabupaten"=>"KABUPATEN HALMAHERA TIMUR"),
            array("id"=>"8207","provinsi_id"=>"82","kabupaten"=>"KABUPATEN PULAU MOROTAI"),
            array("id"=>"8208","provinsi_id"=>"82","kabupaten"=>"KABUPATEN PULAU TALIABU"),
            array("id"=>"8271","provinsi_id"=>"82","kabupaten"=>"KOTA TERNATE"),
            array("id"=>"8272","provinsi_id"=>"82","kabupaten"=>"KOTA TIDORE KEPULAUAN"),
            array("id"=>"9101","provinsi_id"=>"91","kabupaten"=>"KABUPATEN FAKFAK"),
            array("id"=>"9102","provinsi_id"=>"91","kabupaten"=>"KABUPATEN KAIMANA"),
            array("id"=>"9103","provinsi_id"=>"91","kabupaten"=>"KABUPATEN TELUK WONDAMA"),
            array("id"=>"9104","provinsi_id"=>"91","kabupaten"=>"KABUPATEN TELUK BINTUNI"),
            array("id"=>"9105","provinsi_id"=>"91","kabupaten"=>"KABUPATEN MANOKWARI"),
            array("id"=>"9106","provinsi_id"=>"91","kabupaten"=>"KABUPATEN SORONG SELATAN"),
            array("id"=>"9107","provinsi_id"=>"91","kabupaten"=>"KABUPATEN SORONG"),
            array("id"=>"9108","provinsi_id"=>"91","kabupaten"=>"KABUPATEN RAJA AMPAT"),
            array("id"=>"9109","provinsi_id"=>"91","kabupaten"=>"KABUPATEN TAMBRAUW"),
            array("id"=>"9110","provinsi_id"=>"91","kabupaten"=>"KABUPATEN MAYBRAT"),
            array("id"=>"9111","provinsi_id"=>"91","kabupaten"=>"KABUPATEN MANOKWARI SELATAN"),
            array("id"=>"9112","provinsi_id"=>"91","kabupaten"=>"KABUPATEN PEGUNUNGAN ARFAK"),
            array("id"=>"9171","provinsi_id"=>"91","kabupaten"=>"KOTA SORONG"),
            array("id"=>"9401","provinsi_id"=>"94","kabupaten"=>"KABUPATEN MERAUKE"),
            array("id"=>"9402","provinsi_id"=>"94","kabupaten"=>"KABUPATEN JAYAWIJAYA"),
            array("id"=>"9403","provinsi_id"=>"94","kabupaten"=>"KABUPATEN JAYAPURA"),
            array("id"=>"9404","provinsi_id"=>"94","kabupaten"=>"KABUPATEN NABIRE"),
            array("id"=>"9408","provinsi_id"=>"94","kabupaten"=>"KABUPATEN KEPULAUAN YAPEN"),
            array("id"=>"9409","provinsi_id"=>"94","kabupaten"=>"KABUPATEN BIAK NUMFOR"),
            array("id"=>"9410","provinsi_id"=>"94","kabupaten"=>"KABUPATEN PANIAI"),
            array("id"=>"9411","provinsi_id"=>"94","kabupaten"=>"KABUPATEN PUNCAK JAYA"),
            array("id"=>"9412","provinsi_id"=>"94","kabupaten"=>"KABUPATEN MIMIKA"),
            array("id"=>"9413","provinsi_id"=>"94","kabupaten"=>"KABUPATEN BOVEN DIGOEL"),
            array("id"=>"9414","provinsi_id"=>"94","kabupaten"=>"KABUPATEN MAPPI"),
            array("id"=>"9415","provinsi_id"=>"94","kabupaten"=>"KABUPATEN ASMAT"),
            array("id"=>"9416","provinsi_id"=>"94","kabupaten"=>"KABUPATEN YAHUKIMO"),
            array("id"=>"9417","provinsi_id"=>"94","kabupaten"=>"KABUPATEN PEGUNUNGAN BINTANG"),
            array("id"=>"9418","provinsi_id"=>"94","kabupaten"=>"KABUPATEN TOLIKARA"),
            array("id"=>"9419","provinsi_id"=>"94","kabupaten"=>"KABUPATEN SARMI"),
            array("id"=>"9420","provinsi_id"=>"94","kabupaten"=>"KABUPATEN KEEROM"),
            array("id"=>"9426","provinsi_id"=>"94","kabupaten"=>"KABUPATEN WAROPEN"),
            array("id"=>"9427","provinsi_id"=>"94","kabupaten"=>"KABUPATEN SUPIORI"),
            array("id"=>"9428","provinsi_id"=>"94","kabupaten"=>"KABUPATEN MAMBERAMO RAYA"),
            array("id"=>"9429","provinsi_id"=>"94","kabupaten"=>"KABUPATEN NDUGA"),
            array("id"=>"9430","provinsi_id"=>"94","kabupaten"=>"KABUPATEN LANNY JAYA"),
            array("id"=>"9431","provinsi_id"=>"94","kabupaten"=>"KABUPATEN MAMBERAMO TENGAH"),
            array("id"=>"9432","provinsi_id"=>"94","kabupaten"=>"KABUPATEN YALIMO"),
            array("id"=>"9433","provinsi_id"=>"94","kabupaten"=>"KABUPATEN PUNCAK"),
            array("id"=>"9434","provinsi_id"=>"94","kabupaten"=>"KABUPATEN DOGIYAI"),
            array("id"=>"9435","provinsi_id"=>"94","kabupaten"=>"KABUPATEN INTAN JAYA"),
            array("id"=>"9436","provinsi_id"=>"94","kabupaten"=>"KABUPATEN DEIYAI"),
            array("id"=>"9471","provinsi_id"=>"94","kabupaten"=>"KOTA JAYAPURA"),
        );
        Kabupaten::insert($data);
    }
}
